export const PREBUILD_INIT = "PREBUILD_INIT";
export const POST_BUILD_INIT = "POST_BUILD_INIT";
export const GENERATE_STATIC_INIT = "GENERATE_STATIC_INIT";
export const MD_PARSE_READY = "MD_PARSE_READY";
